services:
  - type: web
    name: mi-ebook-bot
    env: python
    runtime: python-3.9  # Especifica la versión exacta
    buildCommand: pip3 install -r requirements.txt  # Usa pip3 explícitamente
    startCommand: python3 -m gunicorn -w 4 -b 0.0.0.0:5000 app:app  # Usa python3 -m gunicorn
    plan: free
    envVar:
      - key: TELEGRAM_BOT_TOKEN
        fromDatabase:
          value: TELEGRAM_BOT_TOKEN
      - key: NOWPAYMENTS_API_KEY
        fromDatabase:
          value: NOWPAYMENTS_API_KEY
      - key: NOWPAYMENTS_SECRET
        fromDatabase:
          value: NOWPAYMENTS_SECRET
      - key: CALLBACK_URL
        value: https://mi-ebook-bot.onrender.com/webhook/nowpayments
